substitutions:
  device_name: esp134-mesure-uv
  adress_ip: "192.168.0.134"
  friendly_name: esp124
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi
  password: !secret mdpwifi

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  reboot_timeout: 5min
  fast_connect: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

sensor:
#ML8511 Mesure UV en mW/Cm²
  - platform: adc
    pin: A0
    name: "esp134_uv"
    unit_of_measurement: "UV"
    update_interval: 60s
    accuracy_decimals: 1
    filters:
      - calibrate_linear:
        - 0.31 -> 0.0
        - 0.88 -> 15.0
# moyenne sur 5 mn
      - sliding_window_moving_average:
          window_size: 5
          send_every: 5  

# Puissance du signal WIFI
  - platform: wifi_signal
    id: wif
    name: "${friendly_name} WiFi Signal Sensor"
    update_interval: 60s
    
# Temps de fonctionnement de l'ESP    
  - platform: uptime
    id: uptime_seconds
    name: "${friendly_name} Uptime"
    update_interval: 60s
    unit_of_measurement: s
    accuracy_decimals: 0
    force_update: false
    icon: mdi:timer


#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    
# Restart de l'ESP
switch:   
  - platform: restart
    name: "${friendly_name} Restart"
    
text_sensor:
# Affichage du temps de fonctionnement
  - platform: template
    name: "${friendly_name} Uptime"
    update_interval: 60s
    icon: mdi:clock-start
    lambda: |-
      int seconds = (id(uptime_seconds).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
      if ( days ) {
        return { (String(days) +"d " + String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else if ( hours ) {
        return { (String(hours) +"h " + String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else if ( minutes ) {
        return { (String(minutes) +"m "+ String(seconds) +"s").c_str() };
      } else {
        return { (String(seconds) +"s").c_str() };
      }
