esphome:
  name: esp131-qualite-air-int
  platform: ESP8266
  board: d1_mini

wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi

  reboot_timeout: 5min
  fast_connect: true
    
  manual_ip:
    static_ip: 192.168.0.131
    gateway: 192.168.0.1
    subnet: 255.255.255.0

# Enable logging
logger:
  baud_rate: 0

api:

ota:

web_server:
  port: 80

uart:
- id: uart_a
  rx_pin: D2
  baud_rate: 9600
  
- id: uart_b
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600


#Etat de la connection
binary_sensor:
  - platform: status
    name: "esp131_Status"

switch:    
  - platform: restart
    name: "ESP131_Restart"
        
sensor:
  - platform: wifi_signal
    name: "ESP131 WiFi Signal Sensor"
    update_interval: 60s

  - platform: pm1006
    uart_id: uart_a
    pm_2_5:
      name: "Concentration Particules 2.5µm"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 50
            send_every: 10 
            send_first_at: 10
            
