substitutions:
  device_name: esp124-tic
  adress_ip: "192.168.0.124"
  friendly_name: esp124
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266  # ESP32             
  board: d1_mini     # mhetesp32minikit


wifi:
  ssid: !secret wifi
  password: !secret mdpwifi

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  reboot_timeout: 5min
  fast_connect: true

# Enable logging
logger:
#  baud_rate: 0
# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

font:
  - file: "fonts/arial.ttf"
    id: arial
    size: 15
  - file: "fonts/arial.ttf"
    id: arial30
    size: 30
  - file: "fonts/arial.ttf"
    id: arial10
    size: 10

i2c:
  sda: GPIO4 #D2=pin 19
  scl: GPIO5 #D1=pin 20
  scan: True
  id: bus_a
  
# 
uart:
  id: uart_a
  rx_pin: GPIO13
#  tx_pin: GPIO1
  baud_rate: 1200
  parity: EVEN
  data_bits: 7

teleinfo:
  id: myteleinfo
  uart_id: uart_a
  update_interval: 10s
  historical_mode: true
  
sensor:
  - platform: teleinfo
    id: hchc
    tag_name: "HCHC"
    name: "Linky HC Wh"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo
    
  - platform: teleinfo
    id: hchp
    tag_name: "HCHP"
    name: "Linky HP Wh"
    unit_of_measurement: "Wh"
    icon: mdi:flash
    teleinfo_id: myteleinfo
    

  - platform: teleinfo
    id: papp
    tag_name: "PAPP"
    name: "Linky PAPP"
    unit_of_measurement: "VA"
    icon: mdi:flash
    teleinfo_id: myteleinfo
    
  - platform: teleinfo
    id: isousc
    tag_name: "ISOUSC"
    name: "Linky I Sousc"
    unit_of_measurement: "A"
    icon: mdi:flash
    teleinfo_id: myteleinfo

  - platform: teleinfo
    id: iinst
    tag_name: "IINST"
    name: "Linky I Inst"
    unit_of_measurement: "A"
    icon: mdi:flash
    teleinfo_id: myteleinfo

  - platform: teleinfo
    id: imax
    tag_name: "IMAX"
    name: "linky I Max"
    unit_of_measurement: "A"
    icon: mdi:flash
    teleinfo_id: myteleinfo

  - platform: template
    name: "Linky I/Imax"
    id: i100
    icon: mdi:flash
    unit_of_measurement: "%"
    lambda: |-
      return (id(iinst).state/id(isousc).state*100);
      
  - platform: homeassistant
    name: "HC J"
    entity_id: sensor.energy_total_linky_usage_daily_hc
    id: hcj

  - platform: homeassistant
    name: "HP J"
    entity_id: sensor.energy_total_linky_usage_daily_hp
    id: hpj

  - platform: wifi_signal
    id: wif
    name: "${friendly_name} WiFi Signal Sensor"
    update_interval: 60s

text_sensor:
  - platform: teleinfo
    tag_name: "OPTARIF"
    name: "Linky OPTARIF"
    teleinfo_id: myteleinfo
    
  - platform: teleinfo
    tag_name: "PTEC"
    name: "Linky PTEC"
    teleinfo_id: myteleinfo

#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

switch:   
  - platform: restart
    name: "${friendly_name} Restart"


display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    brightness: 100%
    lambda: |-
      it.printf(0,0,id(arial),"PuC=%.0f",id(papp).state);
      it.printf(0,15,id(arial),"I Inst=%.0f",id(iinst).state);
      it.printf(64,15,id(arial),"I Max=%.0f",id(imax).state);
      it.printf(0,30,id(arial),"I=%.0f",id(i100).state);
      it.printf(0,45,id(arial),"HCJ=%.0f",id(hcj).state);
      it.printf(64,45,id(arial),"HPJ=%.0f",id(hpj).state);
   