esphome:
  name: esp133-congel
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0

  reboot_timeout: 5min
  
  manual_ip:
    static_ip: 192.168.0.133  
    gateway: 192.168.0.1
    subnet: 255.255.255.0


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80


# Configuration Dalas
dallas:
  - pin: GPIO0

#Etat de la connection
binary_sensor:
  - platform: status
    name: "esp133_Status"

# Individual sensors
sensor:
  - platform: dallas
    address: 0x15006D2B00004B28
    name: "temp_congelo_garage"

switch:
  - platform: restart
    name: "ESP133_Restart"