esphome:
  name: esp136-qualite-air
  platform: ESP8266
  board: d1_mini

  
wifi:
  networks:
    - ssid: !secret wifi
      password: !secret mdpwifi

  reboot_timeout: 5min
  fast_connect: true
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
  #  ssid: "Esp140 Test Fallback Hotspot"
  #  password: "r9UaK4KhGcIW"

  manual_ip:
    static_ip: 192.168.0.136
    gateway: 192.168.0.1
    subnet: 255.255.255.0


# Enable logging
logger:

api:

ota:

web_server:
  port: 80

uart:
  rx_pin: GPIO3 # RX=pin 21
  tx_pin: GPIO1 # TX=pin 22
  baud_rate: 9600

#Etat de la connection
binary_sensor:
  - platform: status
    name: "esp136_Status"

switch:    
  - platform: restart
    name: "ESP136_Restart"
        
sensor:
  - platform: wifi_signal
    name: "ESP136 WiFi Signal Sensor"
    update_interval: 60s

  - platform: mhz19
    co2:
      name: "MH-Z19 CO2 Value"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 10s
    automatic_baseline_calibration: false    