substitutions:
  device_name: esp136-vmc-n0
  adress_ip: "192.168.0.136"
  friendly_name: esp136
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: !secret wifi
  password: !secret mdpwifi


  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  reboot_timeout: 5min
  fast_connect: true

# Enable logging
logger:


# Enable Home Assistant API
api:

ota:

web_server:
  port: 80


# Example configuration entry
dallas:
  - pin: GPIO2 #D4

# Individual sensors
sensor:
  - platform: dallas
    address: 0x0C000004923C0A28
    name: "${friendly_name} T° Air Neuf"
    
  - platform: dallas
    address: 0x2A00000492ADAA28
    name: "${friendly_name} T° Air Vicié"

  - platform: dallas
    address: 0x3E00000492D66328
    name: "${friendly_name} T° insufflation"

  - platform: dallas
    address: 0x4300461100004B28
    name: "${friendly_name} T° aspiration"



#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

switch:   
  - platform: gpio
    name: "${friendly_name} Relais"
    pin: GPIO05 #D1
    id: relais
    
  - platform: template
    name: "${friendly_name} Vit_2"
    id: vit2
    turn_on_action:
      - switch.turn_on: relais
      - delay: 2s
      - switch.turn_off: relais

  - platform: template
    name: "${friendly_name} Vit_3"
    id: vit3
    turn_on_action:
      - switch.turn_on: relais
      - delay: 6s
      - switch.turn_off: relais      

    
  - platform: restart
    name: "${friendly_name} Restart"
    
