substitutions:
  device_name: esp142-test-esp32
  adress_ip: "192.168.0.142"
  friendly_name: esp142
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP32
  board: lolin_d32

wifi:
  ssid: !secret wifi_esp
  password: !secret mdpwifi_esp

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  reboot_timeout: 5min
  fast_connect: true

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
web_server:
  port: 80


sensor:

  - platform: uptime
    name: "ESP142 Uptime Sensor"
    id: esp142_uptime
    update_interval: 10s
  
switch:
  - platform: gpio
    name: "esp142_relais0"
    pin: GPIO0
    id: relay
    
  - platform: restart
    name: "ESP142_Restart"