substitutions:
  device_name: esp129-climat-cellier
  adress_ip: "192.168.0.129"
  friendly_name: esp129
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp

  reboot_timeout: 5min
  fast_connect: true

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0

logger:
api:
ota:
web_server:
  port: 80

time:
  - platform: homeassistant
    timezone:  ${time_timezone} 

#uart:
#  rx_pin: GPIO3 # RX=pin 21
#  tx_pin: GPIO1 # TX=pin 22
#  baud_rate: 9600

i2c:
  sda: GPIO00 #
  scl: GPIO02 #
  scan: true
  id: bus_a

#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

switch:    

  - platform: restart
    name: "${friendly_name} Restart"

sensor:
  - platform: htu21d
    temperature:
      name: "${device_name} Temperature"
    humidity:
      name: "${device_name} Humidité"
    update_interval: 60s
    
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal Sensor"
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime Sensor"
    update_interval: 60s

text_sensor:
  # IP address #
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP address"
      icon: "mdi:network-outline"
    ssid:
      name: "${friendly_name} Connected SSID"
    bssid:
      name: "${friendly_name} Connected BSSID"
  - platform: version
    id: text_sensor_version
    name: "${friendly_name} ESPHome Version"