substitutions:
  device_name: esp125-piscine
  friendly_name: esp125
  adress_ip: "192.168.0.125"
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP32
  board: lolin_d32

wifi:
  networks:
    - ssid: !secret wifi_mi4
      password: !secret mdpwifi_mi4
      priority: 2    
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80


# Example configuration entry for ESP32
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a
  
#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name}_Status"

sensor:

# Mesure du pH
  - platform: ezo
    id: esp125_ph_ezo
    name: ph_ezo
    address: 99
    unit_of_measurement: "pH"
    accuracy_decimals: 2
    update_interval: 15s
# moyenne sur 15 mn
#    filters:
#      - sliding_window_moving_average:
#          window_size: 30
#          send_every: 30  


############### TEMPLATE  ######################"
# Affichage du pH brut (avant filtrage et moyenne)
  - platform: template
    name: "esp125_ph_brut"
    id: ph_brut
    unit_of_measurement: "pH"
    accuracy_decimals: 2
    lambda: |-
      return (id(esp125_ph_ezo).state);

# Mesure de l'ORP
  - platform: ezo
    id: esp125_orp_ezo
    name: orp_ezo
    address: 98
    unit_of_measurement: "mV"
    accuracy_decimals: 1
    update_interval: 60s
# moyenne sur 15 mn
#    filters:
#      - sliding_window_moving_average:
#          window_size: 15
#          send_every: 15           

# Mesure de la pression filtre
  - platform: adc
    pin: A0
    id: esp125_pression_filtre
    name: "Pression filtre"
    unit_of_measurement: "Bars"
    update_interval: 60s
    attenuation: 11db
    filters:
      - calibrate_linear:
        - 0.5 -> 0.0
        - 0.808 -> 0.85
# moyenne sur 30 mn
#      - sliding_window_moving_average:
#          window_size: 30
#          send_every: 30
         

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal Sensor"
    update_interval: 60s

  - platform: homeassistant
    name: "T° Eau Piscine"
    id: temp_piscine
    entity_id: sensor.temp_piscine

# gestion afficheur
display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    update_interval: 5s
    lambda: |-
      it.printf(0,0,"Ph=%.2f",id(esp125_ph_ezo).state);
      it.printf(0,1,"Orp=%.2f",id(esp125_orp_ezo).state);
      it.printf(8,0,"P=%.3f",id(esp125_pression_filtre).state);


switch:    
  - platform: restart
    name: "${friendly_name}_Restart"
    

text_sensor:
  # IP address #
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP address"
      icon: "mdi:network-outline"
    ssid:
      name: "${friendly_name} Connected SSID"
    bssid:
      name: "${friendly_name} Connected BSSID"
  - platform: version
    id: text_sensor_version
    name: "${friendly_name} ESPHome Version"
