substitutions:
  device_name: esp141-test
  adress_ip: "192.168.0.141"
  friendly_name: esp141
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0
  reboot_timeout: 5min
  
  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0

logger:
api:
ota:
web_server:
  port: 80

time:
  - platform: homeassistant
    timezone:  ${time_timezone} 

font:
  - file: "fonts/arial.ttf"
    id: arial
    size: 15
  - file: "fonts/arial.ttf"
    id: arial30
    size: 30
  - file: "fonts/arial.ttf"
    id: arial10
    size: 10
#uart:
#  rx_pin: GPIO3 # RX=pin 21
#  tx_pin: GPIO1 # TX=pin 22
#  baud_rate: 9600
i2c:
  sda: GPIO4 #D2=pin 19
  scl: GPIO5 #D1=pin 20
  scan: True
  id: bus_a

uart:
  rx_pin: GPIO2 #D4
  baud_rate: 9600

#i2c:
#  sda: GPIO00 #
#  scl: GPIO02 #
#  scan: true
#  id: bus_a

#Etat de la connection
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: bp_raz

  - platform: status
    name: "${friendly_name} Status"

switch:    

  - platform: restart
    name: "${friendly_name} Restart"

sensor:

  - platform: homeassistant
    name: "Prod"
    entity_id: sensor.envoy_122103023124_current_power_production
    id: prod

  - platform: homeassistant
    name: "Conso"
    entity_id: sensor.envoy_122103023124_current_power_consumption
    id: conso

  - platform: homeassistant
    name: "Sout"
    entity_id: sensor.envoy_puissance_soutiree_reseau
    id: sout
    
  - platform: homeassistant
    name: "Inj"
    entity_id: sensor.envoy_puissance_injectee_reseau
    id: inj
    
  - platform: wifi_signal
    id: wif
    name: "${friendly_name} WiFi Signal Sensor"
    update_interval: 60s

  - platform: uptime
    id: up
    name: "${friendly_name} Uptime Sensor"
    update_interval: 60s

display:
  - platform: ssd1306_i2c
    model: "SSD1306 64x48"
    reset_pin: D0
    address: 0x3C
    brightness: 100%
    rotation: 0
    lambda: |-
      it.printf(0, 0, id(arial10),"P:%.0f W",id(prod).state);
      it.printf(0, 10, id(arial10),"C:%.0f W",id(conso).state);
      it.printf(0, 20, id(arial10),"S:%.0f W",id(sout).state);
      it.printf(0, 30, id(arial10),"I:%.0f W",id(inj).state);      

#      it.printf(0,0,"PM1.0=%.2f",id(pm1_0).state);
#          it.printf(0, 0, id(arial), "%.1f C", id(temp).state);

