substitutions:
  device_name: esp143-test-esp8266
  adress_ip: "192.168.0.143"
  friendly_name: esp143
  time_timezone: "Europe/Paris"
  
esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini
  platformio_options:
    lib_deps: NeoPixelBus@2.6.0
  on_boot:
    then:
      - light.control:
          id: rgb_led
          brightness: 0.25
          state: on  

wifi:
  networks:
    - ssid: !secret wifi_esp
      password: !secret mdpwifi_esp
      priority: 1
    - ssid: !secret wifi
      password: !secret mdpwifi
      priority: 0
  reboot_timeout: 5min

  manual_ip:
    static_ip: ${adress_ip}
    gateway: 192.168.0.1
    subnet: 255.255.255.0

# Enable logging
logger:


# Enable Home Assistant API
api:

ota:

web_server:
  port: 80


# Led WS2812 RGB  
light:

  - platform: neopixelbus
    method:
      type: esp8266_dma
    num_leds: 8 #1
    pin: GPIO3
    name: "RGB strip"
    variant: ws2812
    id: rgb_led
    default_transition_length: 0s  


sensor:
 # Potentiometre
  - platform: adc
    pin: A0
    id: potar
    name: "${friendly_name} potar"
    unit_of_measurement: "%"
    update_interval: 1s
    accuracy_decimals: 1
    filters:
      - calibrate_linear:
        - 0. -> 0.0
        - 1 -> 100.0
    on_value:
        - if:
            condition:
              sensor.in_range:
                id: potar
                below: 25
            then: 
              - light.addressable_set:
                  id: rgb_led
                  range_from: 0
                  range_to: 1
                  red: 0%
                  green: 100%
                  blue: 0%
                  color_brightness: 100%
              - light.addressable_set:
                  id: rgb_led
                  range_from: 2
                  range_to: 7
                  red: 0%
                  green: 0%
                  blue: 0%
                  color_brightness: 0%   
        - if:
            condition:
              sensor.in_range:
                id: potar
                above: 25
                below: 50
            then: 
              - light.addressable_set:
                  id: rgb_led
                  range_from: 0
                  range_to: 3
                  red: 75%
                  green: 75%
                  blue: 0%
                  color_brightness: 100%
              - light.addressable_set:
                  id: rgb_led
                  range_from: 4
                  range_to: 7
                  red: 0%
                  green: 0%
                  blue: 0%
                  color_brightness: 0%                      
        - if:
            condition:
              sensor.in_range:
                id: potar
                above: 50
                below: 75
            then: 
              - light.addressable_set:
                  id: rgb_led
                  range_from: 0
                  range_to: 5
                  red: 100%
                  green: 50%
                  blue: 0%
                  color_brightness: 100%
              - light.addressable_set:
                  id: rgb_led
                  range_from: 6
                  range_to: 7
                  red: 0%
                  green: 0%
                  blue: 0%                  
                  color_brightness: 0%                  
        - if:
            condition:
              sensor.in_range:
                id: potar
                above: 75
            then: 
              - light.addressable_set:
                  id: rgb_led
                  range_from: 0
                  range_to: 7
                  red: 100%
                  green: 0%
                  blue: 0%
                  color_brightness: 100%



#Etat de la connection
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

switch:   

  - platform: restart
    name: "${friendly_name} Restart"
    
