esphome:
  name: toto

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "8cd3764d96f4635e04a5f2a91ff92bbc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Toto Fallback Hotspot"
    password: "HeA5v7UbphYA"

captive_portal:
    