input_datetime:
  # Horaire Chauffe ECS
  horaire_ecs_debut:
    name: Horaire ECS Début
    has_date: false
    has_time: true
  horaire_ecs_fin:
    name: Horaire ECS Fin
    has_date: false
    has_time: true

input_select:
  ecs_ssol:
    name: Ecs_SSol
    icon: mdi:water-boiler
    options:
      - Auto
      - Arret
      - Marche ECS
      - Marche PV

input_boolean:
  ecs_av_pv:
    name: Ecs PV(=1 avec Routeur PV)
  
sensor:
# Affichage du temps de fonctionnement ce jour
  - platform: history_stats
    name: ECS Chauffage ce jour
    entity_id: binary_sensor.ecs_chauffe
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

binary_sensor:
# Si puissance superieur à 500w = ECS en Marche
  - platform: template
    sensors:
      ecs_chauffe:
        value_template: "{{ states.sensor.ecocompteur_ecs.state | float(default=0) > 500 }}"
        friendly_name: "ECS en Chauffe"
#        device_class: heat