sensor:
# Vantage Pro2 -> WEEXWX
  - platform: mqtt
    name: "VP2_DateTime"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'ms'
    value_template: "{{ value_json.dateTime | round(1) }}"

  - platform: mqtt
    name: "VP2_Temp_Out"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '°C'
    value_template: "{{ value_json.outTemp_C | round(1) }}"

  - platform: mqtt
    name: "VP2_Humidity_Out"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '%'
    value_template: "{{ value_json.outHumidity | round(1) }}"

  - platform: mqtt
    name: "VP2_Barometer"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'mbar'
    value_template: "{{ value_json.barometer_mbar | round(1) }}"
    
#DAILY RAIN (PRECIPITATION QUOTIDIENNE).
#Appuyez sur RAINDAY pour afficher la pluviométrie cumulée depuis minuit.
#Toutes les précipitations cumulées depuis les 24 dernières heures sont affichées dans le bandeau déroulant au bas de l'écran.
  - platform: mqtt
    name: "VP2_Rain"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'mm'
    force_update: true
    value_template: >-
      {% set a=value_json.rain_cm|float(default=0)%}
      {{ (a*10)|round(3) }}     
    

  - platform: mqtt
    name: "VP2_Rain24"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'mm'
    force_update: true
    value_template: >-
      {% set a=value_json.rain24_cm|float(default=0)%}
      {{ (a*10)|round(3) }}

# La Rain Rate (pluviométrie) sera nulle et l'icône parapluie ne sera pas affichée tant que
# deux basculements du pluviomètre ne sont pas survenus dans une période de 15 minutes.
  - platform: mqtt
    name: "VP2_Rain_Rate"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'mm/h'
    force_update: true
    value_template: >-
      {% set a=value_json.rainRate_cm_per_hour|float(default=0)%}
      {{ (a*10)|round(3) }}

#RAIN STORM (AVERSE D'ORAGE).
#Rain Storm (L'averse d'orage) affiche le cumul de pluie de la dernière averse.
#Il faut deux basculements du pluviomètre pour démarrer un événement d'orage et 24 heures sans pluie pour le stopper.
#Appuyez sur RAINDAY pour basculer entre les précipitations quotidiennes et le total d'Averse d'orage.
#Le cumul de pluie peut être affiché en pouces (in) ou millimètres (mm).    
  - platform: mqtt
    name: "VP2_Rain_Storm"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'mm'
    force_update: true
    value_template: >-
      {% set a=value_json.stormRain_cm|float(default=0)%}
      {{ (a*10)|round(3) }}

  - platform: mqtt
    name: "VP2_Rafale"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'km/h'
    value_template: "{{ value_json.windGust_kph | round(2) }}"

  - platform: mqtt
    name: "VP2_Win_Speed"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'km/h'
    value_template: "{{ value_json.windSpeed_kph | round(2) }}"

  - platform: mqtt
    name: "VP2_Win_Dir"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '°'
    value_template: "{{ value_json.windDir | round(1) }}"

  - platform: mqtt
    name: "VP2_Temp_In"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '°C'
    value_template: "{{ value_json.inTemp_C | round(1) }}"

  - platform: mqtt
    name: "VP2_Humidté_In"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '%'
    value_template: "{{ value_json.inHumidity | round(1) }}"

  - platform: mqtt
    name: "VP2_Ressenti"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '°C'
    value_template: "{{ value_json.windchill_C | round(1) }}"

  - platform: mqtt
    name: "VP2_HeatIndex"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: '°C'
    value_template: "{{ value_json.heatindex_C | round(1) }}"

  - platform: mqtt
    name: "VP2_Radiation"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'W/m²'
    value_template: "{{ value_json.radiation_Wpm2 | round(0) }}"

  - platform: mqtt
    name: "VP2_UV"
    state_topic: "home/Vp2/loop"
    unit_of_measurement: 'UV'
    value_template: "{{ value_json.UV | round(1) }}"

  - platform: template
    sensors:
# Azimuth et elevation soleil sont aussi calculés dans ESP134 mais sujet à coupure
      sun_elevation:
        friendly_name: 'elevation soleil'
        unit_of_measurement: "°"
        value_template: "{{'%+.1f'|format(state_attr('sun.sun', 'elevation'))}}"

      sun_azimuth:
        friendly_name: 'azimut soleil'
        unit_of_measurement: "°"
        value_template: "{{'%+.1f'|format(state_attr('sun.sun', 'azimuth'))}}"

# calcul de l'heure lever et coucher du soleil
      heure_leve_soleil:
        friendly_name: 'heure_leve_soleil'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H %M')}}
        icon_template: mdi:weather-sunset-up

      heure_couche_soleil:
        friendly_name: 'heure_couche_soleil'
        value_template: >
          {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %H %M')}}
        icon_template: mdi:weather-sunset-down


# Statistiques Pluviometrie
# sert à gestion robot tonte
  - platform: statistics
    entity_id: sensor.vp2_rain24
    max_age:
      minutes: 320 # sur 6h
    name: vp2_pluviometrie_min
    state_characteristic: value_min

  - platform: statistics
    entity_id: sensor.vp2_rain24
    max_age:
      minutes: 320 # sur 6h
    name: vp2_pluviometrie_max
    state_characteristic: value_max

  - platform: statistics
    entity_id: sensor.vp2_rain24
    max_age:
      minutes: 320 # sur 6h
    name: vp2_pluviometrie_moyenne
    state_characteristic: median

  - platform: statistics
    entity_id: sensor.vp2_rain24
    max_age:
      minutes: 320 # sur 6h
    name: vp2_pluviometrie_standard_deviation
    state_characteristic: standard_deviation

    
input_boolean:
  # Validation notitification alerte météo 
  stop_notif_previ_pluie:
    name: Stop Notif Previ Pluie

