####################################################
#                                                  #
#                     RESEAUX                      #
#                                                  #
####################################################

binary_sensor:
  - platform: ping
    host: 192.168.0.11
    name: "ping_NAS_Dlink"

  - platform: ping
    host: 192.168.0.14
    name: "ping_pc_jeedom"

  - platform: ping
    host: 192.168.0.21
    name: "ping_cam_terrasse"

  - platform: ping
    host: 192.168.0.25
    name: "ping_RPI ADguard"

  - platform: ping
    host: 192.168.0.26
    name: "ping_ECO COMPTEUR"

  - platform: ping
    host: 192.168.0.36
    name: "ping_cam_cuisine"

  - platform: ping
    host: 192.168.0.39
    name: "ping_cam_garage_ext"

  - platform: ping
    host: 192.168.0.47
    name: "ping_Module Adam"

  - platform: ping
    host: 192.168.0.50
    name: "ping_routeur dlink"

  - platform: ping
    host: 192.168.0.54
    name: "ping_cam_salon"

  - platform: ping
    host: 192.168.0.56
    name: "ping_cam_sous_sol"

  - platform: ping
    host: 192.168.0.57
    name: "ping_cam_garage_int"

  - platform: ping
    host: 192.168.0.61
    name: "ping_cam_piscine"

  - platform: ping
    host: 192.168.0.62
    name: "ping_RPI Weewx"

  - platform: ping
    host: 192.168.0.101
    name: "ping_Module Wago Piscine"

#  - platform: ping
#    host: 192.168.0.121
#    name: "ping_Arduino Piscine"

  - platform: group
    name: ping_reseau
    all: true
    device_class: "connectivity"
    entities:
      - binary_sensor.ping_rpi_adguard
      - binary_sensor.ping_module_adam
      - binary_sensor.ping_module_wago_piscine
      - binary_sensor.ping_routeur_dlink
      - binary_sensor.ping_eco_compteur      
      - binary_sensor.ping_cam_cuisine
      - binary_sensor.ping_cam_garage_ext
      - binary_sensor.ping_cam_garage_int
      - binary_sensor.ping_cam_piscine
      - binary_sensor.ping_cam_salon

  #    - binary_sensor.cam_terrasse    

  - platform: group
    name: esp_reseau
    all: true
    device_class: "connectivity"
    entities:
      - binary_sensor.esp123_status
      - binary_sensor.esp124_status
      - binary_sensor.esp125_status
      - binary_sensor.esp129_status
      - binary_sensor.esp130_status
      - binary_sensor.esp131_status
      - binary_sensor.esp132_status
      - binary_sensor.esp133_status
      - binary_sensor.esp135_status
      - binary_sensor.esp137_status
      - binary_sensor.esp138_status
      - binary_sensor.esp139_status
      - binary_sensor.esp142_status
      - binary_sensor.test_reseau

  - platform: group
    name: uptime_reseau
    all: true
    device_class: "connectivity"
    entities:
      - binary_sensor.domo_rem81
      - binary_sensor.jeedom
      - binary_sensor.meteo81000
      - binary_sensor.meteoweewx
      - binary_sensor.ha
      - binary_sensor.motioneye
      - binary_sensor.vtt

  - platform: group
    name: certificats_lets
    all: true
    device_class: "connectivity"
    entities:
      - binary_sensor.certificat_ha
      - binary_sensor.certificat_vtt
      - binary_sensor.certificat_domo
      - binary_sensor.certificat_meteo
      - binary_sensor.certificat_meteo81000
      - binary_sensor.certificat_motioneye
      - binary_sensor.certificat_kobold

template:
  - binary_sensor:
    - name: "Certificat HA"
      unique_id: "certificat_ha"
      state: >-
        {{(state_attr('sensor.cert_expiry_timestamp_ha_rem81_com', 'is_valid'))}}
      device_class: "connectivity"

    - name: "Certificat VTT"
      unique_id: "certificat_vtt"
      state: >-
        {{(state_attr('sensor.cert_expiry_timestamp_vtt_rem81_com', 'is_valid'))}}
      device_class: "connectivity"

    - name: "Certificat DOMO"
      unique_id: "certificat_domo"
      state: >-
        {{(state_attr('sensor.cert_expiry_timestamp_domo_rem81_com', 'is_valid'))}}
      device_class: "connectivity"

    - name: "Certificat Meteo"
      unique_id: "certificat_meteo"
      state: >-
        {{(state_attr('sensor.cert_expiry_timestamp_meteo_rem81_com', 'is_valid'))}}
      device_class: "connectivity"

    - name: "Certificat Meteo 81000"
      unique_id: "certificat_meteo8100"
      state: >-
        {{(state_attr('sensor.cert_expiry_timestamp_meteo81000_rem81_com', 'is_valid'))}}
      device_class: "connectivity"

    - name: "Certificat Motion"
      unique_id: "certificat_motioneye"
      state: >-
        {{(state_attr('sensor.cert_expiry_timestamp_motioneye_rem81_com', 'is_valid'))}}
      device_class: "connectivity"

    - name: "Certificat Kobold"
      unique_id: "certificat_kobold"
      state: >-
        {{(state_attr('sensor.cert_expiry_timestamp_kobold_rem81_com', 'is_valid'))}}
      device_class: "connectivity"

    - name: "test reseau"
      unique_id: "test_reseau"
      state: >-
        {{ is_state('input_boolean.test_alert','on')}}
      device_class: "connectivity"

  - sensor:
    - name: "certificat_ha_fin_nbj"
      unique_id: "certificat_ha_fin_nbj"
      state: >-
        {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_ha_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int }}
      icon: >-
        {% if ((as_timestamp(states('sensor.cert_expiry_timestamp_ha_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int > 31 %}
          mdi:check
        {% else %}
          mdi:alert-octagram
        {% endif %}

      unit_of_measurement: "J"
    - name: "certificat_vtt_fin_nbj"
      unique_id: "certificat_vtt_fin_nbj"
      state: >-
        {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_vtt_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int }}
      icon: >-
        {% if ((as_timestamp(states('sensor.cert_expiry_timestamp_vtt_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int > 31 %}
          mdi:check
        {% else %}
          mdi:alert-octagram
        {% endif %}
      unit_of_measurement: "J"
  
    - name: "certificat_domo_fin_nbj"
      unique_id: "certificat_domo_fin_nbj"
      state: >-
        {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_domo_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int }}
      icon: >-
        {% if ((as_timestamp(states('sensor.cert_expiry_timestamp_domo_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int > 31 %}
          mdi:check
        {% else %}
          mdi:alert-octagram
        {% endif %}
      unit_of_measurement: "J"

    - name: "certificat_meteo_fin_nbj"
      unique_id: "certificat_meteo_fin_nbj"
      state: >-
        {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_meteo_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int }}
      icon: >-
        {% if ((as_timestamp(states('sensor.cert_expiry_timestamp_meteo_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int > 31 %}
          mdi:check
        {% else %}
          mdi:alert-octagram
        {% endif %}
      unit_of_measurement: "J"

    - name: "certificat_meteo81000_fin_nbj"
      unique_id: "certificat_meteo81000_fin_nbj"
      state: >-
        {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_meteo81000_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int }}
      icon: >-
        {% if ((as_timestamp(states('sensor.cert_expiry_timestamp_meteo81000_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int > 31 %}
          mdi:check
        {% else %}
          mdi:alert-octagram
        {% endif %}
      unit_of_measurement: "J"

    - name: "certificat_motioneye_fin_nbj"
      unique_id: "certificat_motioneye_fin_nbj"
      state: >-
        {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_motioneye_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int }}
      icon: >-
        {% if ((as_timestamp(states('sensor.cert_expiry_timestamp_motioneye_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int > 31 %}
          mdi:check
        {% else %}
          mdi:alert-octagram
        {% endif %}
      unit_of_measurement: "J"

    - name: "certificat_kobold_fin_nbj"
      unique_id: "certificat_kobold_fin_nbj"
      state: >-
        {{ ((as_timestamp(states('sensor.cert_expiry_timestamp_kobold_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int }}
      icon: >-
        {% if ((as_timestamp(states('sensor.cert_expiry_timestamp_kobold_rem81_com')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int > 31 %}
          mdi:check
        {% else %}
          mdi:alert-octagram
        {% endif %}
      unit_of_measurement: "J"


