####################################################
#                                                  #
#                     RESEAUX                      #
#                                                  #
####################################################

binary_sensor:

  - platform: ping
    host: 192.168.0.14
    name: "ping_pc_motion"

#  - platform: ping
#    host: 192.168.0.21
#    name: "ping_cam_terrasse"

  - platform: ping
    host: 192.168.0.25
    name: "ping_RPI ADguard"

  - platform: ping
    host: 192.168.0.26
    name: "ping_ECO COMPTEUR"

  - platform: ping
    host: 192.168.0.36
    name: "ping_cam_cuisine"

  - platform: ping
    host: 192.168.0.39
    name: "ping_cam_garage_ext"

  - platform: ping
    host: 192.168.0.47
    name: "ping_Module Adam"

  - platform: ping
    host: 192.168.0.50
    name: "ping_routeur dlink"

  - platform: ping
    host: 192.168.0.54
    name: "ping_cam_salon"

  - platform: ping
    host: 192.168.0.56
    name: "ping_cam_sous_sol"

  - platform: ping
    host: 192.168.0.57
    name: "ping_cam_garage_int"

  - platform: ping
    host: 192.168.0.61
    name: "ping_cam_piscine"

  - platform: ping
    host: 192.168.0.62
    name: "ping_RPI Weewx"

  - platform: ping
    host: 192.168.0.101
    name: "ping_Module Wago Piscine"

#  - platform: ping
#    host: 192.168.0.121
#    name: "ping_Arduino Piscine"

  - platform: group
    name: ping_reseau
    all: true
    device_class: "connectivity"
    entities:
      - binary_sensor.ping_rpi_adguard
      - binary_sensor.ping_module_adam
      - binary_sensor.ping_module_wago_piscine
      - binary_sensor.ping_routeur_dlink
      - binary_sensor.ping_eco_compteur      
      - binary_sensor.ping_cam_cuisine
      - binary_sensor.ping_cam_garage_ext
      - binary_sensor.ping_cam_garage_int
      - binary_sensor.ping_cam_piscine
      - binary_sensor.ping_cam_salon

  #    - binary_sensor.cam_terrasse    

  - platform: group
    name: esp_reseau
    all: true
    device_class: "connectivity"
    entities:
      - binary_sensor.esp123_status
      - binary_sensor.esp124_status
      - binary_sensor.esp125_status
      - binary_sensor.esp129_status
      - binary_sensor.esp130_status
      - binary_sensor.esp132_status
      - binary_sensor.esp133_status
      - binary_sensor.esp135_status
      - binary_sensor.esp137_status
      - binary_sensor.esp138_status
      - binary_sensor.esp139_status
      - binary_sensor.esp140_status
      - binary_sensor.esp142_status
      - binary_sensor.test_reseau

  - platform: group
    name: uptime_reseau
    all: true
    device_class: "connectivity"
    entities:
      - binary_sensor.uptime_domo_rem81
      - binary_sensor.uptime_jeedom
      - binary_sensor.uptime_meteo81000
      - binary_sensor.uptime_meteoweewx
      - binary_sensor.uptime_ha
      - binary_sensor.uptime_motioneye
      - binary_sensor.uptime_vtt
      - binary_sensor.uptime_kobold

mqtt:
  sensor: 

    # Speed Test - Contenair dans NAS OMV
    # https://forum.hacf.fr/t/integrer-speedtest-cli-officielle-a-home-assistant/15436/11
    - name: "speedtest.download"
      state_topic: "speedtest/download"
      unit_of_measurement: Mbit/s
      icon: mdi:speedometer      
      state_class: measurement  

    - name: "speedtest.upload"
      state_topic: "speedtest/upload"
      unit_of_measurement: Mbit/s
      icon: mdi:speedometer      
      state_class: measurement 

    - name: "speedtest.ping"
      state_topic: "speedtest/ping"
      unit_of_measurement: ms      
      icon: mdi:speedometer      
      state_class: measurement  


# https://forum.hacf.fr/t/integrer-speedtest-cli-officielle-a-home-assistant/15436
sensor:
  - platform: command_line
    name: "SpeedTest CLI Data"
    unique_id: speedtest_cli_data
    command: "/config/3rdparty/speedtest/speedtest --format=json --accept-license --accept-gdpr"
    #Toutes les 4 heures, 60 * 60 * 4 = 14400  3600 = 1 heure
    scan_interval: 3600
    command_timeout: 60
    value_template: >-
      {{ 
        { 
          "ping": value_json.ping.latency, 
          "download": value_json.download.bandwidth, 
          "upload": value_json.upload.bandwidth 
        }
        | to_json 
      }}



  # Portainer
  # https://forum.hacf.fr/t/scan-interval-dun-sensor-command-line/5182
  - platform: command_line
    name: "Portainer Online"
    command: response=$(curl -LIk -m 3 http://192.168.0.153:9000 -o /dev/null -w "%{http_code}\n" -s); test "$response" -ge 200 && echo "Online" || echo "Offline"
    scan_interval: 90
    value_template: "{{ value }}"

template:
  - sensor:
      - name: 'SpeedTest CLI Ping'
        unique_id: speedtest_cli_ping
        icon: mdi:speedometer
        unit_of_measurement: ms
        state_class: measurement
        state: "{{ (states('sensor.speedtest_cli_data') | from_json).ping | round(2) }}"
      - name: 'SpeedTest CLI Download'
        unique_id: speedtest_cli_download
        icon: mdi:speedometer
        unit_of_measurement: Mbit/s
        state_class: measurement
        state: "{{ ((states('sensor.speedtest_cli_data') | from_json).download * 8 / 1000 / 1000) | round(2) }}"
      - name: 'SpeedTest CLI Upload'
        unique_id: speedtest_cli_upload
        icon: mdi:speedometer
        unit_of_measurement: Mbit/s
        state_class: measurement
        state: "{{ ((states('sensor.speedtest_cli_data') | from_json).upload * 8 / 1000 / 1000) | round(2) }}"




