input_datetime:
  # Horaire VMC SS
  horaire_vmc_ss_debut:
    name: Horaire VMC SS Début
    has_date: false
    has_time: true
  horaire_vmc_ss_fin:
    name: Horaire VMC SS Fin
    has_date: false
    has_time: true

  # Horaire VMC Niv0
  heure_vmc_niv0_ma:
    name: Heure Ma Ete VMC_N0
    has_date: false
    has_time: true
  heure_vmc_niv0_at:
    name: Heure At Ete VMC_N0
    has_date: false
    has_time: true

input_select:
  vmc_ssol:
    name: Vmc_SSol
    icon: mdi:fan
    options:
      - Auto
      - Marche
      - Arret

  vmc_niv0:
    name: Vmc_Niv0
    icon: mdi:fan
    options:
      - Ete
      - Hiver
      - Marche
      - Arret

input_number:
# Seuil PM2.5 Arret VMC
  seuil_pm2_5_at:
    name: Seuil PM2.5 At VMC
    min: 0
    max: 50
    unit_of_measurement: µg/m3
    step: 1
    icon: mdi:thermometer
    mode: box
# Seuil PM2.5 Marche VMC
  seuil_haut_pm2_5:
    name: Seuil Haut PM2.5 Ma VMC
    min: 0
    max: 500
    unit_of_measurement: µg/m3
    step: 1
    icon: mdi:thermometer
    mode: box
  seuil_tres_haut_pm2_5:
    name: Seuil Tres Haut PM2.5 Ma VMC
    min: 0
    max: 1000
    unit_of_measurement: µg/m3
    step: 11
    icon: mdi:thermometer
    mode: box
    
template:
  - sensor:
# Efficacité de la VMC double Flux
    - name: "Efficacité VMC"
      unique_id: "efficacite_vmc"
      state: >-
        {% set insu = states('sensor.thermometre_temperature') | float(default=0) | round(2) %}
        {% set extr= states('sensor.temperature_salon_zb') | float(default=0) | round(2) %}
        {% set exter = states('sensor.stats_vp2_temp_out') | float(default=0) | round(2) %}
        {% set pu = states('sensor.ecocompteur_vmc_niv0') | float(default=0) | round(2) %}
        {% if (pu<10) or ((insu-exter)/(extr-exter)*100) <=0 %}
            0              
        {% else%}
          {% if ((insu-exter)/(extr-exter)*100) >100 %}
            100
          {% else%}
            {{ ((insu-exter)/(extr-exter)*100) | round(2) }}
          {%endif%}
        {%endif%}
      unit_of_measurement: "%"
      device_class: "aqi"
      state_class: "measurement"  

sensor:
    # Affichage du temps de fonctionnement de la VMC du jour
  - platform: history_stats
    name: temps de Fonctionnement VMC N0
    entity_id: switch.sonoff_vmc_niv0_on_off
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"
