####################################################
#                                                  #
#               VMC NIV0 & SOUS SOL                #
#                                                  #
####################################################

utility_meter:
# usage jour  
  energy_vmc_usage_daily:
    source: sensor.energy_vmc_n0
    cycle: daily
    tariffs:
      - hp
      - hc

input_datetime:
  # Horaire VMC SS
  horaire_vmc_ss_debut:
    name: Horaire VMC SS Début
    has_date: false
    has_time: true
  horaire_vmc_ss_fin:
    name: Horaire VMC SS Fin
    has_date: false
    has_time: true

  # Horaire VMC Niv0
  heure_vmc_niv0_ma:
    name: Heure Ma Ete VMC_N0
    has_date: false
    has_time: true
  heure_vmc_niv0_at:
    name: Heure At Ete VMC_N0
    has_date: false
    has_time: true

input_select:
  vmc_ssol:
    name: Vmc_SSol
    icon: mdi:fan
    options:
      - Auto
      - Marche
      - Arret

  vmc_niv0:
    name: Vmc_Niv0
    icon: mdi:fan
    options:
      - Hor
      - CO2 PM2.5
      - Marche
      - Arret

input_number:
# Seuil PM2.5 Arret VMC
  seuil_pm2_5_at:
    name: Seuil PM2.5 At VMC
    min: 0
    max: 50
    unit_of_measurement: µg/m3
    step: 1
    icon: mdi:chemical-weapon
    mode: box
# Seuil PM2.5 Marche VMC
  seuil_haut_pm2_5:
    name: Seuil Haut PM2.5 Ma VMC
    min: 0
    max: 500
    unit_of_measurement: µg/m3
    step: 1
    icon: mdi:chemical-weapon
    mode: box
  seuil_tres_haut_pm2_5:
    name: Seuil Tres Haut PM2.5 Ma VMC
    min: 0
    max: 1000
    unit_of_measurement: µg/m3
    step: 1
    icon: mdi:chemical-weapon
    mode: box

# Seuil CO2 Arret VMC
  seuil_co2_at:
    name: Seuil CO2 At VMC
    min: 400
    max: 500
    unit_of_measurement: ppm
    step: 1
    icon: mdi:molecule-co2
    mode: box
# Seuil CO2 Marche VMC
  seuil_haut_co2:
    name: Seuil Haut CO2 Ma VMC
    min: 400
    max: 1500
    unit_of_measurement: ppm
    step: 1
    icon: mdi:molecule-co2
    mode: box
  seuil_tres_haut_co2:
    name: Seuil Tres Haut CO2 Ma VMC
    min: 400
    max: 3000
    unit_of_measurement: ppm
    step: 1
    icon: mdi:molecule-co2
    mode: box
    
template:
  - sensor:
    - name: "Energie VMC Jour"
      unique_id: "energy_vmc_daily"
      state: >-
        {% set p = states('sensor.energy_vmc_usage_daily_hp') | float(default=0) | round(2) %}
        {% set o = states('sensor.energy_vmc_usage_daily_hc') | float(default=0) | round(2) %}
        {{ (o + p) | round(2) }}
      unit_of_measurement: "kWh"
      device_class: "energy"
      state_class: "total"  


# Rendement de la VMC double Flux
    - name: "Rendement VMC"
      unique_id: "rendement_vmc"
      state: >-
        {% set insu = states('sensor.thermometre_temperature') | float(default=0) | round(1) %}
        {% set extr= states('sensor.esp136_tdeg_aspiration') | float(default=0) | round(1) %}
        {% set out = states('sensor.esp136_tdeg_air_neuf') | float(default=0) | round(1) %}
        {% set pu = states('sensor.ecocompteur_vmc_niv0') | float(default=0) | round(1) %}
        {% if (pu<10) or (((insu-out)/(extr-out)*100) <=0) %}
            0              
        {% else%}
          {% if ((insu-out)/(extr-out)*100) >= 100 %}
            100
          {% else%}
            {{ ((insu-out)/(extr-out)*100) | round(1) }}
          {%endif%}
        {%endif%}
      unit_of_measurement: "%"
      device_class: "aqi"
      state_class: "measurement"  

  - binary_sensor:
    # Si la puissance electrique est superieure à 10w, on considere que la VMC est en fonctionnement
    - name: "vmc_marche"
      state: >-
        {{states.sensor.ecocompteur_vmc_niv0.state | float(default=0) > 10}}      

sensor:
    # Affichage du temps de fonctionnement de la VMC du jour
  - platform: history_stats
    name: temps de Fonctionnement VMC N0
    entity_id: binary_sensor.vmc_marche
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

# Energie VMC Niv0
  - platform: integration
    source: sensor.ecocompteur_vmc_niv0
    name: energy_vmc_n0
    unit_prefix: k
    #    method: left
    round: 2

# Statistiques puissance 
  - platform: statistics
    name: puissance_vmc_niv0
    entity_id: sensor.ecocompteur_vmc_niv0_brut
    sampling_size: 10
    #max_age:
      # minutes: 30