input_boolean:
  # Gestion volets
  presence_amis_bureau:
    name: Presence Amis Bureau
    icon: mdi:account

  presence_amis_ch_sud:
    name: Presence Amis Chamb Sud
    icon: mdi:account

  presence_amis_ch_nord:
    name: Presence Amis Chamb Nord
    icon: mdi:account

# Calcul Jour/nuit selon luminosite et position du soleil sur l'horizon
  nuit_jour:
    name: Nuit=0/Jour=1
    icon: mdi:weather-sunny

input_datetime:
  # Horaires Volets ete
  horaire_ete_volet_ouv:
    name: Horaire ete volets ouverture
    has_date: false
    has_time: true
  horaire_ete_volet_ferm:
    name: Horaire ete volets fermeture
    has_date: false
    has_time: true

# Horaire surveillance porte
  heure_debut_alarme_porte:
    name: Heure debut alarme portes
    has_date: false
    has_time: true
  heure_fin_alarme_porte:
    name: Heure fin alarme portes
    has_date: false
    has_time: true


input_number:
# Consigne Min/max luminosité 
# gestion volet: Calcul du Input_boolean Nuit/jout
    luminosite_seuil_bas:
      name: Lum. seuil bas
      mode: box
      min: 0
      max: 10
      unit_of_measurement: "Lux"
      icon: mdi:weather-sunny
    luminosite_seuil_haut:
      name: Lum. seuil haut
      mode: box
      min: 10
      max: 50
      unit_of_measurement: "Lux"
      icon: mdi:weather-sunny 

# gestion volet: Niveau Ensoleilement ouv auto volet
    radiation_seuil_ferm_volet:
      name: Radiat seuil ferm volets
      mode: box
      min: 0
      max: 1200
      unit_of_measurement: "w/m2"
      icon: mdi:weather-sunny

# memoire cde volet parents grand
input_text:
  volet_parents_grand:
    initial: ""
  volet_sam_grand:
    initial: ""
  volet_amis_sud_grand:
    initial: ""

binary_sensor:
#inversion d'état pour l'alarme ALARMO
  - platform: template
    sensors:
      porte_garage_non_fermee:
        value_template: >-
          {% if is_state('binary_sensor.porte_garage_fermee', 'on') %}
            off
          {% else %}
            on
          {% endif %} 
      porte_ssol_non_fermee:
        value_template: >-
          {% if is_state('binary_sensor.porte_ssol_fermee', 'on') %}
            off
          {% else %}
            on
          {% endif %} 


input_select:
  volets:
    name: Volets
    icon: mdi:window-shutter
    options:
      - Auto Hiv
      - Auto Ete
      - Absent
      - Arret
cover:
# Convertion TC volet Amis sud grand en cover
  - platform: template
    covers:

      # porte de garage RDC
      garage_rdc:
        device_class: garage
        friendly_name: "Garage RdC"
        unique_id: "garage_rdc"
        value_template: >-
          {% if is_state('binary_sensor.porte_garage_fermee', 'on') %}
            closed
          {% else %}
            open
          {% endif %}     
        open_cover:
          - condition: state
            entity_id: binary_sensor.porte_garage_fermee
            state: "on"
          - service: script.cde_ouv_porte_garage
        close_cover:
          - condition: state
            entity_id: binary_sensor.porte_garage_ouverte
            state: "on"
          - service: script.cde_ferm_porte_garage
        stop_cover:
          service: script.cde_ferm_porte_garage 
        icon_template: >-
          {% if is_state('binary_sensor.porte_garage_fermee', 'on') %}
            mdi:garage
          {% else %} 
            {% if is_state('binary_sensor.porte_garage_ouverte', 'on') %}
            mdi:garage-open
            {% else %}
            mdi:garage-alert
            {% endif %}
          {% endif %}

# Porte de garage Sous Sol
      garage_soussol:
        device_class: garage
        unique_id: "garage_sous_sol"
        friendly_name: "Garage Sous-Sol"
        #value_template: "{{ is_state('binary_sensor.porte_ssol_fermee', 'off')}}"
        value_template: >-
          {% if is_state('binary_sensor.porte_ssol_fermee', 'on') %}
            closed
          {% else %}
            open
          {% endif %}        
        open_cover:
          - condition: state
            entity_id: binary_sensor.porte_ssol_fermee
            state: "on"          
          - service: script.cde2_porte_sous_sol
        close_cover:
          - condition: state
            entity_id: binary_sensor.porte_ssol_ouverte
            state: "on"          
          - service: script.ferm_porte_sous_sol      
        stop_cover:
          service: script.ferm_porte_sous_sol           
        icon_template: >-
          {% if is_state('binary_sensor.porte_ssol_fermee', 'on') %}
            mdi:garage
          {% else %} 
            {% if is_state('binary_sensor.porte_ssol_ouverte', 'on') %}
            mdi:garage-open
            {% else %}
            mdi:garage-alert
            {% endif %}
          {% endif %}

# Volets Proportionnels
# Bureau Droit
  - platform: cover_rf_time_based
    devices:
      volet_bureau_droit_proport:
        name: Volet Droit P
        travelling_time_up: 18
        travelling_time_down: 17
        close_script_entity_id: script.volet_bureau_droit_down
        stop_script_entity_id: script.volet_bureau_droit_stop
        open_script_entity_id: script.volet_bureau_droit_up

# Bureau Gauche
  - platform: cover_rf_time_based
    devices:
      volet_bureau_gauche_proport:
        name: Volet Gauche P
        travelling_time_up: 18
        travelling_time_down: 17
        close_script_entity_id: script.volet_bureau_gauche_down
        stop_script_entity_id: script.volet_bureau_gauche_stop
        open_script_entity_id: script.volet_bureau_gauche_up


# Salle de bains
  - platform: cover_rf_time_based
    devices:
      volet_sdb_proport:
        name: Volet SdB P
        travelling_time_up: 15
        travelling_time_down: 14
        close_script_entity_id: script.volet_sdb_down
        stop_script_entity_id: script.volet_sdb_stop
        open_script_entity_id: script.volet_sdb_up

# Amis Nord
  - platform: cover_rf_time_based
    devices:
      volet_amis_nord_proport:
        name: Volet Amis Nord P
        travelling_time_up: 18
        travelling_time_down: 17
        close_script_entity_id: script.volet_amis_nord_down
        stop_script_entity_id: script.volet_amis_nord_stop
        open_script_entity_id: script.volet_amis_nord_up


# ch parents petit
  - platform: cover_rf_time_based
    devices:
      volet_ch_parent_proport:
        name: Volet ch parent P
        travelling_time_up: 18
        travelling_time_down: 17
        close_script_entity_id: script.volet_ch_parent_down
        stop_script_entity_id: script.volet_ch_parent_stop
        open_script_entity_id: script.volet_ch_parent_up

# ch parents grand
  - platform: cover_rf_time_based
    devices:
      volet_parents_grand_proport:
        name: Volet Parents Grand P
        travelling_time_up: 25
        travelling_time_down: 20
        close_script_entity_id: script.volet_parents_grand_down
        stop_script_entity_id: script.volet_parents_grand_stop
        open_script_entity_id: script.volet_parents_grand_up

# SAM Grand
  - platform: cover_rf_time_based
    devices:
      volet_sam_grand_proport:
        name: Volet sam grand P
        travelling_time_up: 21
        travelling_time_down: 20
        close_script_entity_id: script.volet_sam_grand_down
        stop_script_entity_id: script.volet_sam_grand_stop
        open_script_entity_id: script.volet_sam_grand_up

# ch amis sud
  - platform: cover_rf_time_based
    devices:
      volet_amis_sud_proport:
        name: Volet amis sud P
        travelling_time_up: 21
        travelling_time_down: 19
        close_script_entity_id: script.volet_amis_sud_down
        stop_script_entity_id: script.volet_amis_sud_stop
        open_script_entity_id: script.volet_amis_sud_up

# SAM Grand
  - platform: cover_rf_time_based
    devices:
      volet_amis_sud_grand_proport:
        name: Volet amis sud grand P
        travelling_time_up: 29
        travelling_time_down: 29
        close_script_entity_id: script.volet_amis_sud_grand_down
        stop_script_entity_id: script.volet_amis_sud_grand_stop
        open_script_entity_id: script.volet_amis_sud_grand_up



